Issue #1   code reivew
UofS-Pulse-Binfo/user_charts pull request #3
Opened 2017-05-25 18:28 UTC by reynoldtan

In this issue, logic in handling submitted form value does not match the other visualization systems in this module. For ease of maintainability, I have implemented a similar form submit value handling process, particularly for hooks hook_validate() and hook_submit() in beanplot. 

Other enhancements and improvements include, adding doc block style comment/description in overall source code, made error more descriptive, created a separate step for chart options, replaced text placeholders (lorems), used Drupal theme table instead of JavaScript to construct summary data table and reused existing JS library.

To test.

1. Item #1 - Use description (Code Review), Item #3 - Tweak wording (Code Review), Item #1 - #description (e7187dc) and Item #2 - Fill out column details (e7187dc)   : click User-driven Charts to load the main page for this module. Please review text description under Beanplot. Once reviewed, please access Beanplot link to load the main form/page. Please review text description of Trait form field, instruction regarding full dataset text field and text information of highlight germplasm checkbox.

2. Item #3 - Make fieldset (e7187dc), Item #4 - Should be Step #3 (e7187dc) and Item #4 - Move chart options (Code Review) : In the beanplot page, please review fieldset titled "Step 2 Customize Display"

3. Item #9, Item #10 and Item #11 - Informative error for missing column and non numeric mean (e7187dc) : To test this fix, type in a trait name, and load the following dataset.
Location A	2015	GERM:5	
Location A	2015	GERM:5	37
Location A	2015	GERM:2	38
Location A	2015	GERM:3	r
Location A	2015	GERM:5	39
	2015	GERM:1	39

The first and last lines should indicate a missing column while a non numeric value provided in line 4.

4.  Finally, please try to create a beanplot chart - one without customizations and the other with summary table and another with selected germplasm.

Thank you!

2017-05-26 01:46 UTC, laceysanderson requested changes
## Code Review:
Comments have been added directly to the pull request. The following lists the requested changes and whether the solution is approved :-) :
- [ ] Set description on menu item. (new suggestion in the commit).
- [x] Re-use the existing saveSVGasPNG.js.
- [x] Tweak wording/format of the form (not all comments were addressed).
- [x] Move Chart options into their own fieldset: `Step #3 Customize Display`
- [x] See https://github.com/UofS-Pulse-Binfo/user_charts/blob/master/forms/pcoa_scatterplot.form.inc#L161 for an example of how to handle the "Show Example". Please be consistent for maintainability reasons and to ensure the example is treated exactly the same as user entered data for both validation and chart drawing.
- [x] Don't use javascript to generate your summary table. Instead do this in the drupal form by accessing $form_state['processed'] and using a markup form element (see example below).
- [x] js/beanplot.chart.js could use more comments. Functions should have a full on docblock like in PHP.
- [ ] form_set_error() should be called when each error is detected. The Drupal Form API will handle compiling of multiple errors and theme-ing them accordingly. In other words, replace adding errors to $arr_errors with a call to form_set_error() directly (see example in comments on code).

2017-05-26 01:46 UTC, laceysanderson commented on user_charts.module
> +    'description' => 'Draws a beanplot to show visual comparison of data between groups',
Oh, I had suggested one in the comments on the commit but you must have missed it:
"Allows users to draw a chart showing the distribution of phenotype values for a number of site years."

Yours is also correct by the way, just not as specific to our data :-)

2017-05-26 01:46 UTC, laceysanderson commented on user_charts.module
> +    'description' => 'Draws a beanplot to show visual comparison of data between groups',
Perhaps we should also change the title here to "Phenotype Beanplot".

2017-05-26 01:46 UTC, laceysanderson commented on forms/beanplot.form.inc
> +          // A line must contain 4 columns.
You should call form_set_error() directly at this point instead of adding to $arr_errors. The Drupal Form API handles compiling of multiple errors.
```php
form_set_error('data', t($line_error['missing_col'], array(
  '%i' => $i + 1,   // Line counter.
  '%line' => $line, // Current line.
  '%columns' => count($cols)
));
```

2017-05-26 01:46 UTC, laceysanderson commented on forms/beanplot.form.inc
> +      form_set_error('data', theme('item_list', array('items' => $arr_errors)));
Do not make this call to form_set_error().

2017-05-29 20:23 UTC, reynoldtan commented on forms/beanplot.form.inc
> +          // A line must contain 4 columns.
Works fine for single error, but in multiple line errors, only the first error is shown.

![screen shot 2017-05-29 at 2 19 24 pm](https://cloud.githubusercontent.com/assets/15472253/26561267/2baf4524-447a-11e7-9c20-d4775811a48d.png)

2017-05-30 04:04 UTC, laceysanderson commented on forms/beanplot.form.inc
> +          // A line must contain 4 columns.
I could have sworn that the Drupal Form API handled this better but further searching has confirmed that only the first error is shown as you pointed out. I stand corrected 👍

2017-05-30 04:05 UTC, laceysanderson commented on forms/beanplot.form.inc
> +      form_set_error('data', theme('item_list', array('items' => $arr_errors)));
This suggestion is in reference to the previous comment which has been shown to be incorrect. As such, ignore this suggestion as well.

2017-06-06 17:28 UTC, laceysanderson commented
Tested the functionality and it works perfectly 👍

2017-06-06 17:29 UTC, laceysanderson approved these changes

2017-06-06 17:29 UTC, merged